/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#3e2400',
        'on-secondary-fixed-variant': '#005236',
        'surface-container-highest': '#353436',
        'on-error-container': '#ffdad6',
        'on-primary': '#002e6a',
        'on-surface': '#e5e2e3',
        'secondary-fixed': '#6ffbbe',
        'inverse-primary': '#005ac2',
        'on-primary-fixed': '#001a42',
        'tertiary-fixed-dim': '#ffb95f',
        'tertiary-container': '#ca8100',
        'surface-variant': '#353436',
        'on-secondary-container': '#00311f',
        'secondary-fixed-dim': '#4edea3',
        'inverse-surface': '#e5e2e3',
        'surface-dim': '#131314',
        'on-background': '#e5e2e3',
        'surface-container-low': '#1c1b1c',
        'surface-container-high': '#2a2a2b',
        'primary-fixed': '#d8e2ff',
        'on-secondary-fixed': '#002113',
        'on-primary-fixed-variant': '#004395',
        'outline-variant': '#27272A',
        'surface-container-lowest': '#0e0e0f',
        'on-tertiary': '#472a00',
        secondary: '#4edea3',
        'on-error': '#690005',
        'on-secondary': '#003824',
        'inverse-on-surface': '#313031',
        error: '#ffb4ab',
        outline: '#8c909f',
        surface: '#131314',
        'error-container': '#93000a',
        'tertiary-fixed': '#ffddb8',
        background: '#0A0A0B',
        'on-primary-container': '#00285d',
        'surface-container': '#201f20',
        'surface-tint': '#adc6ff',
        'on-tertiary-fixed': '#2a1700',
        'on-surface-variant': '#c2c6d6',
        'primary-container': '#4d8eff',
        'surface-bright': '#3a393a',
        'secondary-container': '#00a572',
        tertiary: '#ffb95f',
        primary: '#adc6ff',
        'primary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed-variant': '#653e00',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-margin-mobile': '16px',
        gutter: '16px',
        'component-gap': '12px',
        'container-margin-desktop': '32px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'data-mono-lg': ['JetBrains Mono', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-mono-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
